---

# NTP
ntp_timezone: Asia/Kolkata
ntp_cron_handler_enabled: true

# Bootparams
boot_params_present:
  - systemd.unified_cgroup_hierarchy=1

# Docker
docker_add_nonroot_users: true
docker_nonroot_users:
  - ubuntu

# Tailscale
# See vault/common.yml for tailscale_auth_key

# CNI
cni_version: 1.0.1

# TLS
tls_base_dir: files/tls
tls_consul_dir: "{{ tls_base_dir }}/consul"
tls_nomad_dir: "{{ tls_base_dir }}/nomad"

# Consul
consul_version: 1.10.2
consul_datacenter: dc1
# See vault/common.yml for consul_encrypt_key
consul_ca_src_file: "{{ tls_consul_dir }}/ca/consul-agent-ca.pem"
consul_cert_src_file: "{{ tls_consul_dir }}/{{ inventory_hostname }}/{{ consul_datacenter }}-{{ consul_role }}-consul-0.pem"
consul_key_src_file: "{{ tls_consul_dir }}/{{ inventory_hostname }}/{{ consul_datacenter }}-{{ consul_role }}-consul-0-key.pem"

# Nomad
nomad_version: 1.1.5
nomad_region: global
nomad_datacenter: dc1
nomad_ca_src_file: "{{ tls_nomad_dir }}/ca/nomad-agent-ca.pem"
nomad_cert_src_file: "{{ tls_nomad_dir }}/{{ inventory_hostname }}/{{ nomad_region }}-{{ 'server' if nomad_role != 'client' else 'client' }}-nomad-0.pem"
nomad_key_src_file: "{{ tls_nomad_dir }}/{{ inventory_hostname }}/{{ nomad_region }}-{{ 'server' if nomad_role != 'client' else 'client' }}-nomad-0-key.pem"
nomad_consul_ca_src_file: "{{ tls_consul_dir }}/ca/consul-agent-ca.pem"
nomad_consul_cert_src_file: "{{ tls_consul_dir }}/cli/{{ consul_datacenter }}-cli-consul-0.pem"
nomad_consul_key_src_file: "{{ tls_consul_dir }}/cli/{{ consul_datacenter }}-cli-consul-0-key.pem"

nomad_host_volumes:
  - name: traefik
    path: /mnt/neo/nomad/traefik
    read_only: false
    mode: "0777"

nomad_host_networks:
  - name: private
    cidr_or_interface: "{{ ansible_default_ipv4.interface }}"
    reserved_ports: [22]
  - name: tailscale
    cidr_or_interface: "{{ ansible_tailscale0.device }}"
    reserved_ports: [22]
  - name: localhost
    cidr_or_interface: lo
    reserved_ports: [22]

# NFS
autofs_maps:
  - name: nfs_nomad
    mountpoint: /mnt/neo
    options:
      - "--timeout 60"
    directories:
      - path: nomad
        server: "192.168.0.101:/mnt/neo/nomad" # TODO: Don't hardcode IP
        options:
          - fstype=nfs4
          - rw
          - hard
          - intr
          - nodev
          - nosuid
          - async
