---

consul_version: 1.10.0
consul_iface: tailscale0
consul_client_address: "{{ ansible_tailscale0.ipv4.address }} {{ ansible_docker0.ipv4.address | default('') }} 127.0.0.1"
dnsmasq_config: |
  no-resolv
  # For consul domain
  server=/consul/127.0.0.1#8600
  # For remaining
  server=1.1.1.1
  server=8.8.8.8
  interface=tailscale0
  interface=docker0
  bind-dynamic

consul_tls_enable: true
consul_tls_copy_keys: true
consul_tls_ca_crt: "{{ tls_dir_consul_ca }}/consul-agent-ca.pem"
# consul_tls_ca_src_dir: "{{ tls_dir_consul_ca }}"
# consul_tls_cert_src_dir: "{{ tls_dir_consul }}/{{ inventory_hostname }}"
# consul_tls_key_src_dir: "{{ tls_dir_consul }}/{{ inventory_hostname }}"
consul_tls_verify_incoming: true
consul_tls_verify_outgoing: true
consul_tls_verify_incoming_rpc: true
consul_tls_verify_incoming_https: true
consul_tls_verify_server_hostname: true
consul_ports_http: -1
consul_ports_https: 8501
