---

nomad_version: 1.1.2
nomad_iface: tailscale0
nomad_bootstrap_expect: 1 # Currently when nomad_use_consul is true, this is being set wrongly
nomad_use_consul: true
nomad_cni_enable: true
nomad_podman_enable: true
nomad_podman_version: 0.3.0
nomad_plugins:
  nomad-driver-podman:
    config:
      socket_path: unix://run/user/1000/podman/podman.sock
      volumes:
        enabled: true
      recover_stopped: true

# TLS related
nomad_encrypt_enable: true
nomad_tls_enable: true
nomad_tls_copy_keys: true
nomad_ca_src_dir: "{{ tls_dir_nomad_ca }}"
nomad_cert_src_dir: "{{ tls_dir_nomad }}/{{ inventory_hostname }}"
nomad_key_src_dir: "{{ tls_dir_nomad }}/{{ inventory_hostname }}"