---

- name: Create job
  hosts: nas0
  tasks:
    - name: Load nomad vars
      include_vars: file=nomad_jobs/vars.yml
    - name: Deploy nomad jobs
      community.general.nomad_job:
        host: "{{ ansible_tailscale0.ipv4.address }}"
        use_ssl: no
        state: present
        content: "{{ lookup('template', '{{ item }}') }}"
        timeout: 120
      with_fileglob:
        - nomad_jobs/*.nomad
        - nomad_jobs/*.nomad.j2
