---
# Playbook

- name: Ready nodes (Disable IPv6, APT maintainance, Install Tailscale)
  hosts: all
  roles:
    - role: ansible_disable_ipv6
      become: true
    - role: bootstrap
    - role: ansible_tailscale
      when: ansible_tailscale0 is not defined # add a check to see if we got an ip address

# TODO: Make this role better for mirrored / raidz configurations
- name: Setup ZFS
  hosts: nas
  roles:
    - role: ansible_zpool

# TODO: Make this role better for multiple NAS boxes
- name: Create required zfs datasets
  hosts: nas
  tasks:
    - name: Create datasets
      become: true
      zfs:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
        extra_zfs_properties: "{{ item.props | default('{}') }}"
      loop: "{{ datasets }}"

- name: Install docker and podman
  hosts: nomad_clients
  roles:
    - ansible_docker
    - ansible_podman

- name: Install consul
  become: true
  hosts: consul_instances
  roles:
    - role: ansible_consul
    - role: ansible_dnsmasq

- name: Install nomad
  become: true
  hosts: nomad_instances
  roles:
    - role: ansible_nomad
