---
# Playbook

- name: Ready the pi(s)
  hosts: rpi
  roles:
    - bootstrap

# - name: Install consul
#   become: true
#   hosts: consul_instances
#   roles:
#     - ansible_consul

# - name: Install nomad
#   become: true
#   hosts: nomad_instances
#   vars:
#     nomad_plugins:
#       nomad-driver-podman:
#         config:
#           socket_path: unix://run/user/1000/podman/podman.sock
#           volumes:
#             enabled: true
#             selinuxlabel: z
#           recover_stopped: true
#   roles:
#     - ansible_nomad
