---

- name: Ready nodes
  hosts: all
  roles:
    - role: role-ntp
      become: true
    - blmhemu.general.bootparams
    - blmhemu.general.bootstrap
    - role-tailscale
    - role-docker
  tasks:
    - include_tasks: tasks/network-online.yml

# NFS server and client
- name: Ready NFS Server
  hosts: nas0
  pre_tasks:
    - include_tasks: tasks/btrfs.yml
    - include_tasks: tasks/nfs_dirs.yml
  roles:
    - role: robertdebock.roles.nfsserver
      become: true

- name: Mount nfs on nomad clients
  hosts: nomad_clients:!nas0
  roles:
    - role: robertdebock.roles.autofs
      become: true

- name: Ready consul cluster
  hosts: consul_instances
  pre_tasks:
    - include_tasks: tasks/tls_consul.yml
  roles:
    - blmhemu.general.consul
    - blmhemu.general.dnsmasq

- name: Ready cni
  hosts: nomad_clients
  roles:
    - blmhemu.general.cni

- name: Ready nomad cluster
  hosts: nomad_instances
  pre_tasks:
    - include_tasks: tasks/tls_nomad.yml
  roles:
    - blmhemu.general.nomad

# WIP
# - name: Ready vault cluster
#   hosts: vault_servers
#   pre_tasks:
#     - include_tasks: tasks/tls_vault.yml
#   roles:
#     - blmhemu.general.vault
