---

- name: Ready NFS Server
  hosts: nas0
  pre_tasks:
    - include_tasks: tasks/btrfs.yml
  roles:
    - role: robertdebock.roles.nfsserver
      become: true

#- name: Mount nfs on nomad instances
#  hosts: nomad_instances | difference('nas0')
#  tasks:
#    - debug: var=ansible_host
#  roles:
#    - role: robertdebock.roles.nfsserver

#- name: Setup consul cluster
#  hosts: consul_instances
#  pre_tasks:
#    - include_tasks: tasks/tls_consul.yml
#  roles:
#    - blmhemu.general.consul
#
#- name: Setup nomad cluster
#  hosts: nomad_instances
#  pre_tasks:
#    - include_tasks: tasks/tls_nomad.yml
#  roles:
#    - blmhemu.general.nomad

# Need to have some roles for NAS
