---
# tasks file for ansible_podman

- name: Add gpg key of kubic project
  become: true
  apt_key:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_{{ ansible_distribution_version }}/Release.key
    state: present

- name: Add kubic project repo
  become: true
  apt_repository:
    repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /
    filename: devel:kubic:libcontainers:stable
    state: present
    update_cache: yes

- name: Install podman
  become: true
  apt:
    name:
      - podman
      - slirp4netns
      - uidmap
      - fuse-overlayfs
    state: present

- name: Enable podman socket for this user
  systemd:
    name: podman.socket
    state: started
    enabled: yes
    daemon-reload: yes
    scope: user

- name: Enable podman service for this user
  systemd:
    name: podman
    state: started
    enabled: yes
    daemon-reload: yes
    scope: user

- name: Ensure lingering enabled for this user
  command:
    cmd: loginctl enable-linger {{ ansible_user }}
    creates: /var/lib/systemd/linger/{{ ansible_user }}
