---
# Meant to be used in btrfs.yml

- name: Check if subvol already exists
  become: true
  stat:
    path: "{{ btrfs_mount_dir }}/{{ item.name }}"
  register: subvol_stat

# Create a block
- block:
    - name: Create subvol
      become: true
      command: btrfs subvolume create "{{ btrfs_mount_dir }}/{{ item.name }}"

    - name: Set permissions for subvol
      become: true
      file:
        path: "{{ btrfs_mount_dir }}/{{ item.name }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode | default('0644') }}"
        state: directory
  when:
    - not subvol_stat.stat.exists
    - item.state is not defined or item.state != "absent"

- name: Cleanup absent subvol
  become: true
  command: btrfs subvolume delete "{{ btrfs_mount_dir }}/{{ item.name }}"
  when: subvol_stat.stat.exists and item.state is defined and item.state == "absent"
