---

- name: Check if {{ item.path }} exists
  become: true
  stat:
    path: "{{ item.path }}"
  register: item_stat

- name: Create {{ item.path }}
  become: true
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('nobody') }}"
    group: "{{ item.group | default('nogroup') }}"
    mode: "{{ item.mode | default('0777') }}"
    attr: "{{ item.attr | default('') }}"
    state: directory
  when: not item_stat.stat.exists
