---

- name: Ensure required host vols exist
  become: true
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('nobody') }}"
    group: "{{ item.group | default('nogroup') }}"
    mode: "{{ item.mode | default('0777') }}"
    state: directory
  with_items: "{{ nomad_host_volumes }}"
