---

# NTP
ntp_timezone: Asia/Kolkata
ntp_cron_handler_enabled: true

# Bootparams
boot_params_present:
  - systemd.unified_cgroup_hierarchy=1

# Docker
docker_add_nonroot_users: true
docker_nonroot_users:
  - ubuntu

# Tailscale
# tailscale_authkey: Encrypted in vars.vault.yml

# TLS
tls_base_dir: files/tls
tls_consul_dir: "{{ tls_base_dir }}/consul"
tls_nomad_dir: "{{ tls_base_dir }}/nomad"
tls_vault_dir: "{{ tls_base_dir }}/vault"

# Consul
consul_version: 1.12.2
consul_datacenter: dc1
consul_bind_addr: "{{ '{{' }} GetInterfaceIP \\\"tailscale0\\\" {{ '}}' }}"
consul_retry_join_interface: "ansible_tailscale0"
consul_ca_src_file: "{{ tls_consul_dir }}/ca/consul-agent-ca.pem"
consul_cert_src_file: "{{ tls_consul_dir }}/{{ inventory_hostname }}/{{ consul_datacenter }}-{{ consul_role }}-consul-0.pem"
consul_key_src_file: "{{ tls_consul_dir }}/{{ inventory_hostname }}/{{ consul_datacenter }}-{{ consul_role }}-consul-0-key.pem"
# consul_encrypt_key: Encrypted in vars.vault.yml

# Dnsmasq
dnsmasq_config: |
  no-resolv
  # For consul
  server=/consul/127.0.0.1#8600
  # For remaining
  server=9.9.9.9
  server=1.1.1.1
  interface=lo
  interface=docker0
  bind-dynamic
resolv_config: |
  nameserver 127.0.0.1
  nameserver {{ ansible_docker0.ipv4.address }}
  options trust-ad

# Vault
vault_region: dc1
vault_ca_src_file: "{{ tls_vault_dir }}/ca/vault-agent-ca.pem"
vault_cert_src_file: "{{ tls_vault_dir }}/{{ inventory_hostname }}/{{ vault_region }}-server-vault-0.pem"
vault_key_src_file: "{{ tls_vault_dir }}/{{ inventory_hostname }}/{{ vault_region }}-server-vault-0-key.pem"

# CNI
cni_version: 1.1.1

# Nomad
nomad_version: 1.3.1
nomad_region: global
nomad_datacenter: dc1
nomad_bind_addr: "{{ '{{' }} GetInterfaceIP \\\"tailscale0\\\" {{ '}}' }}"
nomad_http_addr: "127.0.0.1 {{ '{{' }} GetInterfaceIP \\\"tailscale0\\\" {{ '}}' }} {{ '{{' }} GetInterfaceIP \\\"{{ ansible_default_ipv4.interface }}\\\" {{ '}}' }}"
nomad_http_adv_addr: "{{ nomad_bind_addr }}"
nomad_ca_src_file: "{{ tls_nomad_dir }}/ca/nomad-agent-ca.pem"
nomad_cert_src_file: "{{ tls_nomad_dir }}/{{ inventory_hostname }}/{{ nomad_region }}-{{ 'server' if nomad_role != 'client' else 'client' }}-nomad-0.pem"
nomad_key_src_file: "{{ tls_nomad_dir }}/{{ inventory_hostname }}/{{ nomad_region }}-{{ 'server' if nomad_role != 'client' else 'client' }}-nomad-0-key.pem"
nomad_consul_ca_src_file: "{{ tls_consul_dir }}/ca/consul-agent-ca.pem"
nomad_consul_cert_src_file: "{{ tls_consul_dir }}/cli/{{ consul_datacenter }}-cli-consul-0.pem"
nomad_consul_key_src_file: "{{ tls_consul_dir }}/cli/{{ consul_datacenter }}-cli-consul-0-key.pem"
nomad_docker_allow_privileged: true
nomad_host_networks:
  - name: default
    cidr_or_interface: "{{ ansible_default_ipv4.interface }}"
    reserved_ports: [22]
  - name: tailscale
    cidr_or_interface: "{{ ansible_tailscale0.ipv4.address }}/32"
    reserved_ports: [22]
  - name: localhost
    cidr_or_interface: lo
    reserved_ports: [22]
# nomad_telemetry_enable: true