---

# NTP
ntp_timezone: Asia/Kolkata
ntp_cron_handler_enabled: true

# Bootparams
boot_params_present:
  - systemd.unified_cgroup_hierarchy=1

# Docker
docker_add_nonroot_users: true
docker_nonroot_users:
  - ubuntu

# Tailscale
# See vault/common.yml for tailscale_auth_key

# CNI
cni_version: 1.0.1

# TLS
tls_base_dir: files/tls
tls_consul_dir: "{{ tls_base_dir }}/consul"
tls_nomad_dir: "{{ tls_base_dir }}/nomad"

# Consul
consul_version: 1.10.3
consul_datacenter: dc1
consul_bind_addr: "{{ ansible_default_ipv4.address }}" # https://github.com/hashicorp/consul/issues/11198
# consul_encrypt_key in vars.vault.yml
consul_ca_src_file: "{{ tls_consul_dir }}/ca/consul-agent-ca.pem"
consul_cert_src_file: "{{ tls_consul_dir }}/{{ inventory_hostname }}/{{ consul_datacenter }}-{{ consul_role }}-consul-0.pem"
consul_key_src_file: "{{ tls_consul_dir }}/{{ inventory_hostname }}/{{ consul_datacenter }}-{{ consul_role }}-consul-0-key.pem"

# Dnsmasq
dnsmasq_config: |
  no-resolv
  # For consul
  server=/consul/127.0.0.1#8600
  # For remaining
  server=1.1.1.1
  server=8.8.8.8
  interface=lo
  interface=docker0
  bind-dynamic

resolv_config: |
  nameserver 127.0.0.1
  nameserver {{ ansible_docker0.ipv4.address }}
  options trust-ad

# Nomad
nomad_version: 1.1.5
nomad_region: global
nomad_datacenter: dc1
nomad_ca_src_file: "{{ tls_nomad_dir }}/ca/nomad-agent-ca.pem"
nomad_cert_src_file: "{{ tls_nomad_dir }}/{{ inventory_hostname }}/{{ nomad_region }}-{{ 'server' if nomad_role != 'client' else 'client' }}-nomad-0.pem"
nomad_key_src_file: "{{ tls_nomad_dir }}/{{ inventory_hostname }}/{{ nomad_region }}-{{ 'server' if nomad_role != 'client' else 'client' }}-nomad-0-key.pem"
nomad_consul_ca_src_file: "{{ tls_consul_dir }}/ca/consul-agent-ca.pem"
nomad_consul_cert_src_file: "{{ tls_consul_dir }}/cli/{{ consul_datacenter }}-cli-consul-0.pem"
nomad_consul_key_src_file: "{{ tls_consul_dir }}/cli/{{ consul_datacenter }}-cli-consul-0-key.pem"
# nomad_telemetry_enable: true
nomad_host_volumes:
  - name: traefik
    path: /mnt/neo/nomad/traefik
    read_only: false
  - name: nextcloud_db
    path: /mnt/neo/nomad/nextcloud/db
    read_only: false
  - name: nextcloud_data
    path: /mnt/neo/nomad/nextcloud/data
    read_only: false
  - name: heimdall
    path: /mnt/neo/nomad/heimdall
    read_only: false
nomad_host_networks:
  - name: default
    cidr_or_interface: "{{ ansible_default_ipv4.interface }}"
    reserved_ports: [22]
  - name: tailscale
    cidr_or_interface: "{{ ansible_tailscale0.ipv4.address }}/32"
    reserved_ports: [22]
  - name: localhost
    cidr_or_interface: lo
    reserved_ports: [22]

# NFS
autofs_maps:
  - name: nfs_nomad
    mountpoint: /mnt/neo
    options:
      - "--timeout 60"
    directories:
      - path: nomad
        server: "192.168.0.101:/mnt/neo/nomad" # TODO: Don't hardcode IP
        options:
          - fstype=nfs4
          - rw
          - hard
          - intr
          - nodev
          - nosuid
          - async
