---

btrfs_disk: /dev/disk/by-id/ata-ST6000VN0033-2EE110_ZAD9J1J4
btrfs_label: neo
btrfs_mount_dir: /mnt/{{ btrfs_label }}
btrfs_subvols:
  - nomad
  - sed

nfsserver_exports:
  - share: "{{ btrfs_mount_dir }}/nomad"
    hosts:
      - name: 192.168.0.0/24
        options:
          - rw
          - async
          - no_subtree_check
