# Host variables for nas0
---
ansible_host: 192.168.0.101
consul_node_role: client
nomad_node_role: client
nomad_docker_enable: true
os_disk: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  33376265333763323265313237303862386537636633303861336235636261326632383164373162
  6533323935653363326130376235343439626338653862310a303162626135663162323864646664
  61663263363362343232363266633865376637333236643639303264656236316539323630393236
  3738653466643064610a346136363338346665353635306330643637343032303562346564353839
  62393465393136313631383036613735343430653561393538303065656563346439663533373233
  3437393861353531303133623063616465353730323538363735
disk_id: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66656663356336303566656262623638353035383137396539363666396639353062663361306433
  6663343134393131313966613435333231323135386464340a666438316638383735663763323130
  30666339323834383731306461666130383566363365663666303638303135386137343964626233
  3737613235363037330a343234346338633162353961386537353038633938396634333735616635
  39316338656632356264386139613237616330303833353266633732366438383638613036633839
  6435376335336133363634376332386139353766656131376463
pool_name: neo
base_mount_point: /mnt
pool_mount_point: "{{ base_mount_point }}/{{ pool_name }}"
datasets:
  # How to select sensible props -
  # 1. https://davidstephens.uk/ansible-nas/zfs/zfs_configuration/
  # 2. https://jrs-s.net/2018/08/17/zfs-tuning-cheat-sheet/
  # The first item is the whole pool. Try not to f-up.
  - name: "{{ pool_name }}"
    props: compression=zstd atime=off
  # Movies and shows are large and already compressed
  - name: "{{ pool_name }}/flix"
    props: recordsize=1M compression=off exec=off
  - name: "{{ pool_name }}/flix/downloads"
  - name: "{{ pool_name }}/flix/tv"
  - name: "{{ pool_name }}/flix/movies"
  # Config files do not take much space.
  - name: "{{ pool_name }}/config"
    props: compression=off
  - name: "{{ pool_name }}/config/traefik"
  - name: "{{ pool_name }}/config/fbr"
  - name: "{{ pool_name }}/config/snr"
  - name: "{{ pool_name }}/config/rdr"
  - name: "{{ pool_name }}/config/bzr"
  - name: "{{ pool_name }}/config/jkt"
  - name: "{{ pool_name }}/config/qbt"
  # These are important data
  - name: "{{ pool_name }}/drive/fbr"
  - name: "{{ pool_name }}/drive/syn"
  - name: "{{ pool_name }}/drive/ete"
# Nomad is not fun for stateful workloads
nomad_host_volumes:
  - name: eted
    path: "{{ pool_mount_point }}/drive/ete"
    owner: ubuntu
    group: ubuntu
    mode: u=rwx,g=r,o=r
    read_only: false
  - name: fbrd
    path: "{{ pool_mount_point }}/drive/fbr"
    owner: ubuntu
    group: ubuntu
    mode: u=rwx,g=r,o=r
    read_only: false
  - name: synd
    path: "{{ pool_mount_point }}/drive/syn"
    owner: ubuntu
    group: ubuntu
    mode: u=rwx,g=r,o=r
    read_only: false
  - name: traefikc
    path: "{{ pool_mount_point }}/config/traefik"
    owner: ubuntu
    group: ubuntu
    mode: u=rwx,g=r,o=r
    read_only: false
  - name: fbrc
    path: "{{ pool_mount_point }}/config/fbr"
    owner: ubuntu
    group: ubuntu
    mode: u=rwx,g=r,o=r
    read_only: false
  - name: bzrc
    path: "{{ pool_mount_point }}/config/bzr"
    owner: ubuntu
    group: ubuntu
    mode: u=rwx,g=r,o=r
    read_only: false
  - name: jktc
    path: "{{ pool_mount_point }}/config/jkt"
    owner: ubuntu
    group: ubuntu
    mode: u=rwx,g=r,o=r
    read_only: false
  - name: rdrc
    path: "{{ pool_mount_point }}/config/rdr"
    owner: ubuntu
    group: ubuntu
    mode: u=rwx,g=r,o=r
    read_only: false
  - name: snrc
    path: "{{ pool_mount_point }}/config/snr"
    owner: ubuntu
    group: ubuntu
    mode: u=rwx,g=r,o=r
    read_only: false
  - name: qbtc
    path: "{{ pool_mount_point }}/config/qbt"
    owner: ubuntu
    group: ubuntu
    mode: u=rwx,g=r,o=r
    read_only: false
  - name: flixd
    path: "{{ pool_mount_point }}/flix/downloads"
    owner: ubuntu
    group: ubuntu
    mode: u=rw,g=r,o=r
    read_only: false
  - name: flixt
    path: "{{ pool_mount_point }}/flix/tv"
    owner: ubuntu
    group: ubuntu
    mode: u=rw,g=r,o=r
    read_only: false
  - name: flixm
    path: "{{ pool_mount_point }}/flix/movies"
    owner: ubuntu
    group: ubuntu
    mode: u=rw,g=r,o=r
    read_only: false