---

btrfs_disk: /dev/disk/by-id/ata-ST6000VN0033-2EE110_ZAD9J1J4
btrfs_label: neo
btrfs_mount_dir: /mnt/{{ btrfs_label }}
btrfs_subvols:
  - name: nomad
    owner: nobody
    group: nogroup
    mode: 777
    # Optionally, state: "present" or "absent"

nfsserver_exports:
  - share: "{{ btrfs_mount_dir }}/nomad"
    hosts:
      - name: 192.168.0.0/24
        options:
          - rw
          - async
          - root_squash
          - no_subtree_check
          - insecure # Not really insecure. Read https://security.stackexchange.com/questions/246527/what-is-insecure-about-the-insecure-option-of-nfs-exports
